--!strict
-- GENERATED by tools/map/build_sky_islands.py - do not edit by hand.
-- Landing islands for FlightService: top-centre position, radius, zone and the landing pad
-- (each island Model in workspace.SkyIslands also has an invisible 'LandingPad' part).

export type Island = { Name: string, Zone: string, Top: Vector3, Radius: number, Pad: Vector3 }

local IslandConfig: { Islands: { Island } } = {
	Islands = {
		{ Name = "MeadowRest", Zone = "MeadowSky", Top = Vector3.new(-70, 150, -56), Radius = 30, Pad = Vector3.new(-70, 150, -52) },
		{ Name = "WindmillHill", Zone = "MeadowSky", Top = Vector3.new(72, 350, -48), Radius = 32, Pad = Vector3.new(64, 350, -40) },
		{ Name = "RainbowShelf", Zone = "CloudShelf", Top = Vector3.new(-66, 560, 62), Radius = 34, Pad = Vector3.new(-60, 560, 68) },
		{ Name = "SummitCloud", Zone = "CloudShelf", Top = Vector3.new(70, 1100, 62), Radius = 36, Pad = Vector3.new(70, 1100, 70) },
	},
}

return IslandConfig
